#!/usr/bin/env ruby
number = 0
while number < 100
  number += 1
  case
  when number % 3 == 0 && number % 5 == 0
    puts 'fizzbuzz'
  when number % 3 == 0
    puts 'fizz'
  when number % 5 == 0
    puts 'buzz'
  else
    puts number
  end
end