# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'minitest'

group :development do
  gem 'rubocop-fjord', require: false
  # gem 'rubocop-rails'
end
